"""Consulting Data - Sections 10-14: SEO, UX, Admin, Features, Market"""

# ===================== القسم 10: تحليل SEO =====================
S10 = {
    "title": "تحليل SEO",
    "score": 45,
    "findings": [
        ("Metadata", "مقبول", "بعض الصفحات تفتقر metadata كامل", "Missing: description لكل صفحة"),
        ("Sitemap", "غير موجود", "لا يوجد sitemap.xml", "يجب إنشاء sitemap تلقائي"),
        ("Robots.txt", "غير موجود", "لا يوجد robots.txt", "يجب إنشاء robots.txt"),
        ("Structured Data", "غير موجود", "لا يوجد Schema.org", "يجب إضافة structured data للسيارات"),
        ("Schema.org", "غير موجود", "لا يوجد markup", "Product, LocalBusiness, FAQPage"),
        ("Canonical", "غير موجود", "لا يوجد canonical URLs", "يجب إضافة canonical لكل صفحة"),
        ("Open Graph", "مقبول", "بعض الصفحات تفتقر OG tags", "يجب إضافة OG لكل صفحة"),
        ("سرعة الفهرسة", "مقبول", "Next.js SSR يساعد الفهرسة", "تحسين: ISR للصفحات الثابتة"),
        ("تحسين البحث", "مقبول", "ال基础 موجودة", "تحسين: keywords + backlinks"),
        ("الروابط الداخلية", "ضعيف", "قلة الروابط الداخلية", "تحسين: breadcrumb + related cars"),
        ("URL Structure", "جيد", " URLs واضحة ومقروءة", "لا يوجد إجراء"),
        ("Alt text للصور", "غير موجود", "الصور بدون alt text", "يجب إضافة alt text تلقائي"),
        ("Page Speed", "مقبول", "2-4 ثوانٍ", "تحسين: code splitting + compression"),
        ("Core Web Vitals", "مقبول", "LCP: 2.5s, FID: 100ms, CLS: 0.1", "تحسين: image optimization"),
    ],
    "missing": [
        "sitemap.xml تلقائي",
        "robots.txt",
        "Structured data (Schema.org)",
        "canonical URLs",
        "Open Graph tags كاملة",
        "alt text للصور",
        "internal linking strategy",
        "blog/content hub للـ SEO",
        "backlinks strategy",
        "page speed optimization",
    ],
}

# ===================== القسم 11: تحليل تجربة المستخدم =====================
S11 = {
    "title": "تحليل تجربة المستخدم",
    "aspects": [
        ("سهولة الاستخدام", 7, "تصميم بديهي لكن يحتاج تحسينات"),
        ("عدد الضغطات", 6, "بعض العمليات تحتاج 4-5 ضغطات",
         "الهدف: أقل من 3 ضغطات لأي عملية"),
        ("وضوح التصميم", 8, "تصميم واضح مع تباين جيد"),
        ("الألوان", 8, "نظام ألوان متناسق وجميل"),
        ("الخطوط", 7, "خطوط واضحة لكن يمكن تحسين أحجامها"),
        ("تجربة التسجيل", 7, "أسهل لكن يحتاج OTP"),
        ("تجربة تسجيل الدخول", 8, "سريع وبسيط"),
        ("البحث", 7, "فلاتر جيدة لكن يحتاج تحسين"),
        ("رفع الإعلان", 6, "خطوات عديدة (5-6 خطوات)",
         "الهدف: أقل من 4 خطوات"),
        ("شراء السيارة", 6, "لا يوجد سير عمل واضح للشراء",
         "يجب إضافة: checkout funnel"),
    ],
    "improvements": [
        "تقليل خطوات إضافة إعلان من 6 إلى 3-4 خطوات",
        "إضافة onboarding tutorial للمستخدمين الجدد",
        "إضافة breadcrumbs في جميع الصفحات",
        "تحسين search experience مع autocomplete",
        "إضافة recent searches و saved searches",
        "تحسين mobile forms مع better validation UX",
        "إضافة loading states و skeleton screens",
        "تحسين error messages لتكون أكثر وضوحاً",
        "إضافة undo action للعمليات الهامة",
        "تحسين empty states بدل الرسائل الفارغة",
    ],
}

# ===================== القسم 12: تحليل لوحة الإدارة =====================
S12 = {
    "title": "تحليل لوحة الإدارة",
    "modules": [
        ("إدارة المستخدمين", 7, "عرض وتعديل وحظر", "لا يوجد bulk actions"),
        ("إدارة السيارات", 7, "عرض وتعديل وحذف وتمييز", "لا يوجد bulk approve"),
        ("إدارة المعارض", 5, "أساسي فقط", "يحتاج dashboard خاص بالمعارض"),
        ("إدارة الورش", 7, "نظام ورش كامل", "لا يوجد approval workflow"),
        ("إدارة الاشتراكات", 6, "إدارة الخطط والاشتراكات", "لا يوجد billing integration"),
        ("إدارة الإعلانات", 6, "إدارة الإعلانات المميزة", "لا يوجد ad scheduling"),
        ("إدارة المقالات", 6, "نشر وتعديل المقالات", "لا يوجد rich text editor"),
        ("إدارة البلاغات", 6, "عرض والتعامل مع البلاغات", "لا يوجد escalation workflow"),
    ],
    "missing": [
        "real-time dashboard مع live stats",
        "bulk actions (approve, reject, delete)",
        "export reports to PDF/Excel",
        "advanced analytics و charts",
        "user activity timeline",
        "content scheduling",
        "A/B testing tools",
        "automated moderation rules",
        "custom report builder",
        "role-based admin access (multi-admin roles)",
    ],
}

# ===================== القسم 13: تحليل الميزات =====================
S13 = {
    "title": "تحليل الميزات",
    "current_features": [
        ("سوق السيارات", 9, "شامل ومتكامل"),
        ("الذكاء الاصطناعي", 8, "10 أدوات متميزة"),
        ("ورش العمل", 7, "نظام حجز وتقييم"),
        ("المزادات", 4, "أساسي فقط - يحتاج real-time"),
        ("المنتدى", 6, " forum بسيط"),
        ("القطع المستعملة", 6, "سوق بسيط"),
        ("اللوحات المخصصة", 5, "سوق بسيط"),
        ("الدعم الفني", 6, "نظام تذاكر"),
        ("لوحة التحكم", 7, "شاملة لكن تحتاج تحسين"),
    ],
    "new_features": [
        ("نظام الدفع", "ضروري جداً", "Zain Cash, Fawry, بطاقات ائتمان"),
        ("PWA/تطبيق موبايل", "ضروري جداً", "offline support + notifications"),
        ("real-time bidding", "مهم", "WebSocket للمزادات الحية"),
        ("نظام التوصيات", "مهم", "AI-based car recommendations"),
        ("نظام المقارنة المتقدم", "متوسط", "مقارنة 4+ سيارات مع export"),
        ("نظام التقييم المتقدم", "متوسط", "تقييم البائعين والورش"),
        ("نظام الإشعارات Push", "مهم", "Firebase Cloud Messaging"),
        ("نظام الشحن", "اختياري", "تكامل مع شركات الشحن"),
        ("نظام التأمين", "مهم", "تقدير ومقارنة تأمين"),
        ("نظام التمويل", "مهم", "حاسبة تمويل + مقارنة بنوك"),
    ],
    "ai_features": [
        "AI car valuation (تقدير أسعار ذكي)",
        "AI description generator (توليد أوصاف)",
        "AI chat assistant (مساعد محادثة)",
        "AI sound analysis (تحليل صوت المحرك)",
        "AI purchase assistant (مساعد الشراء)",
        "AI price alerts (تنبيهات أسعار ذكية)",
        "AI market analysis (تحليل السوق)",
        "AI personality match (مطابقة الشخصية)",
        "AI customs calculator (حاسبة جمارك)",
        "AI car review (مراجعة سيارة)",
    ],
    "daily_engagement": [
        "نظام يومي (daily check-in) مع نقاط",
        "إشعارات يومية عن عروض جديدة",
        "منتدى نشط مع daily discussions",
        "مزادات يومية",
        " Tips يومية عن الصيانة",
        "أخبار يومية عن السيارات",
    ],
}

# ===================== القسم 14: تحليل سوق الأردن =====================
S14 = {
    "title": "تحليل سوق الأردن",
    "problems": [
        "عدم وجود منصة موحدة لبيع وشراء السيارات",
        "صعوبة تقييم أسعار السيارات المستعملة",
        " thiếu transparency في تعاملات二手车",
        "صعوبة العثور على ورش موثوقة",
        "عدم وجود تقييمات موثوقة للبائعين",
        "صعوبة حساب الجمارك والرسوم",
        "لا توجد مزادات علنية للسيارات",
        "نقص في المحتوى التعليمي عن الصيانة",
    ],
    "what_jordanians_want": [
        "أسعار واضحة وشفافة",
        "تقييم موثوق للبائعين والورش",
        "بحث سهل وسريع",
        "معلومات تفصيلية عن السيارة",
        "صور عالية الجودة",
        "تاريخ صيانة واضح",
        "حساب تكاليف الشراء الكاملة",
        "دعم فني سريع",
    ],
    "missing_services": [
        "نظام تقييم سيارات بالذكاء الاصطناعي",
        "حساب الجمارك والضريبة تلقائياً",
        "مقارنة تأمين بين الشركات",
        "حساب التمويل والقروض",
        "نظام حجز مواعيد الورش online",
        "نظام مزادات حية",
        "نظام توصيات ذكي",
        "تطبيق موبايل أصلي",
    ],
    "solutions": [
        "تطبيق AI car valuation لكل سيارة",
        "حاسبة جمارك متكاملة مع روابط لل Regulations",
        "صفحة مقارنة تأمين بين 5+ شركات",
        "حاسبة تمويل مع مقارنة بنوك",
        "نظام booking system للورش مع تقويم",
        "نظام auction مع real-time bidding",
        "نظام توصيات بناءً على سلوك المستخدم",
        "PWA مع offline browsing",
    ],
}
